config/routes.rb
Rails.application.routes.draw do
  root 'time_entries#index'
  resources :time_entries do
    get 'weekly', on: :collection
  end
  resources :sessions

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/signout', to: "sessions#destroy", as: :signout
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user

  def self.find_from_authhash(authhash)
    find_by(authhash_to_attributes(authhash))
  end

  def self.create_from_authhash(authhash,user=nil)
    info = authhash['info']
    user ||= User.create!(email: info['email'], first_name: info['first_name'], last_name: info['last_name'])
    user.authentications.create!(self.authhash_to_attributes(authhash))
  end

  private

  def self.authhash_to_attributes(authhash)
    {uid: authhash['uid'],authprovider: authhash['provider']}
  end
end

app/models/time_entry.rb
class TimeEntry < ActiveRecord::Base
  belongs_to :user
  
  validates_numericality_of :time, greater_than: 0 
  validates_numericality_of :distance, greater_than_or_equal_to: 0
  validates_presence_of :date
  before_save :fill_week

  def self.in_range(from,to)
    if from.nil? and to.nil?
      all
    elsif from.present? and to.present?
      where(date:(from..to))
    elsif from.present?
      where('date >= ?',from)
    else
      where('date <= ?', to)
    end
  end
  
  def self.sums_by_week
    select('sum(time_entries.distance) as total_distance,sum(time_entries.time) as total_time,time_entries.week').group(:week)
  end
  
  def weekly_average_speed
    raise NoMethodError.new('weekly_average_speed can be called only instances returned by sums_by_week') if total_distance.nil? 
    total_distance/total_time.to_f
  end
  
  def average_speed
    distance/time.to_f
  end

  def time_in_minutes
    time.nil? ? nil : time/60
  end

  def time_in_minutes=(value)
    self.time=(value.nil? ? nil : value.to_i*60)
  end
  
  def self.week_info(week)
    cwyear = week/53
    cweek = week%53+1
    {year: cwyear, week: cweek, start:DateTime.commercial(cwyear,cweek) ,end:(DateTime.commercial(cwyear,cweek)+6.days).end_of_day}
  end

  private

  def fill_week
    datetime = self.date.to_datetime
    self.week = datetime.cwyear*53+(datetime.cweek-1)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authentications, dependent: :destroy

  has_many :time_entries, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :require_login

  private

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def current_user=(user)
    @current_user = user
    if user == nil then
      session[:user_id] = nil
    else
      session[:user_id] = user.id
    end
  end

  def signed_in?
    !!current_user
  end

  def require_login
    if not signed_in?
      flash[:alert] = 'Log in'
      redirect_to new_session_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login

  def new
  end

  def create
    auth_hash = request.env['omniauth.auth']
    unless auth = Authentication.find_from_authhash(auth_hash)
      auth=Authentication.create_from_authhash(auth_hash, current_user)
    end
    self.current_user = auth.user
    redirect_to root_url, :notice => "Signed in!"
  end
end

app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
  def create
    params = time_entries_param
    
    errors={}
    if params.has_key?(:date)
      params[:date] = Time.zone.parse(params[:date])
    else
      datetime_str = params[:date_s][:date]+" "+params[:date_s][:time]
      begin
        params[:date]=DateTime.strptime(datetime_str,'%m/%d/%Y %H:%M')
        params.delete(:date_s)
      rescue
        params.delete(:date_s)
        errors[:date]="unable to parse date"
      end
    end 
    
    @time_entry = current_user.time_entries.build params

    respond_to do |format|
      if errors.empty? and @time_entry.save
        format.html { redirect_to action: :index }
        format.js { head :no_content }
        format.json { render json: {status: 'ok', time_entry:@time_entry }}
      else
        if not errors.empty?
          @time_entry.valid?
          errors = @time_entry.errors.to_hash.merge(errors)
        else
          errors = @time_entry.errors.to_hash
        end
        format.html { render :new }
        format.json { render json: {errors: errors}, status: :unprocessable_entity} 
        format.js { render json: {errors: errors}, status: :unprocessable_entity } 
      end
    end
  end

  def index
    from,to = from_to_params
    @from_time = from
    @to_time = to
    @time_entries = current_user.time_entries.in_range(from,to)
    @time_entry = TimeEntry.new(user:current_user, date:DateTime.now)
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @time_entries.to_json(json_opts) }
    end
  end

  def weekly
    from,to = from_to_params
    @time_entries = current_user.time_entries.in_range(from,to)
    sums_by_week = @time_entries.sums_by_week
    @sums_by_week = sums_by_week.map {|s| {week: TimeEntry.week_info(s.week), average: s.weekly_average_speed, distance:s.total_distance}}
  end

  private
  
  def from_to_params
    range=[params[:start],params[:end]]
    range.map! do |timestr|
      if not timestr.blank? 
        DateTime.strptime(timestr,'%m/%d/%Y')
      end
    end
    [range[0].try(:beginning_of_day),range[1].try(:end_of_day)]
  end
 
  def time_entries_param
    params.require(:time_entry).permit(:time_in_minutes,:time,:distance,:date,date_s:[:time,:date])
  end

  def json_opts
    {only: [:date,:time,:distance]}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/time_entries_helper.rb
module TimeEntriesHelper
  def number_to_human_speed(speed_in_m_per_s)
    speed_in_km_h = speed_in_m_per_s*3.6
    number_to_human(speed_in_km_h)+" km/h"
  end

  def time_as_minutes(seconds)
    seconds.nil? ? nil : seconds/60
  end

  def mintes_as_time(minutes)
    mintues.nil? ? nil : minutes*60
  end  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JoggingTimes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JoggingTimes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="session-container">
  <%= yield %>
</div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
<div id="errorExplanation">
  <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>
  <ul>
  <% target.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/time_entries/_form.html.erb
<% options||={} %>
<div class="jumbotron">
<%= form_for time_entry,{html: {role:"form"}}.merge(options[:form_options] || {}) do |f| %>
    <%= render partial: 'shared/error_messages', locals: {target: f.object }%>
	<div class="field">
	  <%= f.label :date %>
	  <div class="field-input">
		<div class="row">
		  <div class="col-xs-8 col-md-4"> 
		    <div class="input-group date">
	          <%= text_field_tag 'date[date]', f.object.date.try(:strftime,'%m/%d/%Y'), data: {behaviour: 'datepicker'} %>
		      <span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
		    </div>
	      </div>
          <div class="col-xs-4 col-md-2">
            <%= text_field_tag 'date[time]', f.object.date.try(:strftime,'%H:%M') ,placeholder: "HH:MM" %>
	      </div>
	    </div>
	    <span class="help-block">Date in MM/DD/YYYY HH:MM format</span>
	  </div>
	  
	</div>
	<div class="field">
	  <%= f.label :time %>
	  <div class="field-input">
		<div class='input-group'>
  	    	<%= f.number_field :time_in_minutes %>
			<span class="input-group-addon">minutes</span>
		</div>
		<span class="help-block">Duration of the run in minutes</span>
	  </div>
	  
	</div>
	<div class="field">
  	  <%= f.label :distance %>
	  <div class="field-input">
		<div class='input-group'>
	      <%= f.number_field :distance %>
	  	  <span class="input-group-addon">meters</span>
		</div>
		<span class="help-block">Distance of the run meters</span>
	  </div>
	  
	</div>
	<div class="submit">
	  <div class="submit-button">
	    <%= f.submit %>
	  </div>
    </div>
<% end %>
</div>

app/views/time_entries/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">joglog</a>
    </div>
    <form class="navbar-form navbar-right date-range-search" role="search">
      <div class="input-daterange input-group" id="datepicker">
        <input type="text" class="input form-control from-date" name="start" placeholder="dd/mm/yyyy" value="<%= @from_time.try(:to_s,:picker) %>" />
        <span class="input-group-addon">to</span>
        <input type="text" class="input form-control to-date" name="end" placeholder="dd/mm/yyyy" value="<%= @to_time.try(:to_s,:picker) %>" />
        <span class="input-group-btn">
          <button class="btn btn-default range-search" type="submit"><span class="glyphicon glyphicon-search"></span></button>
        </span>
      </div>
    </form>
    <ul class="nav navbar-nav navbar-right">
      <li class="<%= act == :index ? "active" : ""%>"><a href="<%= time_entries_url %>">Entries <span class="glyphicon glyphicon-list"></span></a></li> 
      <li class="<%= act == :weekly ? "active" : ""%>"><a href="<%= weekly_time_entries_url %>">Weekly <span class="glyphicon glyphicon-stats"></span></a></li>
    </ul>
  </div>
</nav>

app/views/time_entries/index.html.erb
<%= render partial: 'navbar', locals: {act: :index} %>

<div class='row'>
  <div class='col-xs-8'>
    <h1>Time entries</h1>
  </div>
  <div class='col-xs-4'>
    <button class="btn new-time-entry pull-right" data-toggle="modal" data-target="#new-time-entry-modal"><span class="glyphicon glyphicon-plus"></span> New entry</button>
  </div>
</div>

<table class="time-entries">
  <thead>
	<tr>
	  <th>Date</th>
	  <th>Duration</th>
	  <th>Distance</th>
	  <th>Average speed</th>
    </tr>
  </thead>
  <tbody>
	<% @time_entries.each do |time_entry| %>
	  <tr>
	  	<td><%= l time_entry.date, format: :short %></td>
	  	<td><%= distance_of_time_in_words(time_entry.time.seconds) %></td>
	  	<td><%= number_to_human(time_entry.distance,units: :distance) %></td>
	  	<td><%= number_to_human_speed(time_entry.average_speed) %></td>
	  </tr>
	<% end %>
  </tbody>
</table>



<div class="modal fade" id="new-time-entry-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">New entry</h4>
      </div>
      <div class="modal-body">
		 <%= form_for @time_entry,remote: true, html: {role:"form", class:"form-horizontal new-time-entry"} do |f| %>
		    <%= render partial: 'shared/error_messages', locals: {target: f.object }%>
		 	<div class="form-group date">
		 	  <%= f.label :date, class:"control-label" %>
		 	  <div class="field-input">
		 		<div class="row">
		 		  <div class="col-datetime-date"> 
		 		    <div class="input-group date">
		 	          <%= text_field_tag 'time_entry[date_s][date]', f.object.date.try(:strftime,'%m/%d/%Y'), data: {behaviour: 'datepicker'}, placeholder: "MM/DD/YYYY", class:"form-control"  %>
		 		      <span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
		 		    </div>
		 	      </div>
		           <div class="col-datetime-time">
		             <%= text_field_tag 'time_entry[date_s][time]', f.object.date.try(:strftime,'%H:%M') ,placeholder: "HH:MM", class:"form-control" %>
		 	      </div>
		 	    </div>
		 	    <span class="help-inline">Date in MM/DD/YYYY HH:MM format</span>
		 	  </div>
	  
		 	</div>
		 	<div class="form-group time">
		 	  <%= f.label :time_in_minutes, 'Time', class:"control-label" %>
		 	  <div class="field-input">
		 		<div class='input-group'>
		   	    	<%= f.number_field :time_in_minutes, class:"form-control" %>
		 			<span class="input-group-addon">minutes</span>
		 		</div>
		 		<span class="help-inline">Duration of the run in minutes</span>
		 	  </div>
	        </div>
		 	<div class="form-group distance">
		   	  <%= f.label :distance, class:"control-label" %>
		 	  <div class="field-input">
		 		<div class='input-group'>
		 	      <%= f.number_field :distance, class:"form-control" %>
		 	  	  <span class="input-group-addon">meters</span>
		 		</div>
		 		<span class="help-inline">Distance of the run meters</span>
		 	  </div>
	  
		 	</div>
			<div class="modal-footer">
		 	  <div class="submit from-group">
		 	    <div class="submit-button">
		 	      <%= f.submit class:"btn" %>
		 	    </div>
		      </div>
		    </div>
		 <% end %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/time_entries/new.html.erb
<h1>New time entry</h1>

<%= render partial: 'form', locals: {time_entry: @time_entry}%>

app/views/time_entries/weekly.html.erb
<%= render partial: 'navbar', locals: {act: :weekly} %>

<h1>Weekly report</h1>

<table class="time-entries">
  <thead>
	<tr>
	  <th>Week</th>
	  <th>Total distance</th>
	  <th>Average speed</th>
    </tr>
  </thead>
  <tbody>
	<% @sums_by_week.each do |sum| %>
	  <tr>
	  	<td><%= sum[:week][:year] %>/<%= sum[:week][:week] %></td>
	  	<td><%= number_to_human(sum[:distance],units: :distance) %></td>
	  	<td><%= number_to_human_speed(sum[:average]) %></td>
	  </tr>
	<% end %>
  </tbody>
</table>